//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCES = "LOGIN_SUCCES"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "LOGIN_REQUEST"
export const CLEAR_ERROR_SUCCES = "LOGIN_SUCCES"
export const CLEAR_ERROR_FAILURE = "LOGIN_FAILURE"